module.import('Tetris.js').then(Tetris=>{
    let
        tetris,
        mainDiv=document.createElement('div'),
        boardDiv=document.createElement('div'),
        holdDiv=document.createElement('div'),
        nextDiv=document.createElement('div'),
        statusDiv=document.createElement('div')
    mainDiv.id='div_game'
    mainDiv.style.position='fixed'
    mainDiv.style.backgroundColor='darkgray'
    mainDiv.style.top='50%'
    mainDiv.style.left='50%'
    mainDiv.style.marginTop='-240px'
    mainDiv.style.marginLeft='-320px'
    mainDiv.style.width='640px'
    mainDiv.style.height='480px'
    boardDiv.id='div_board'
    boardDiv.style.position='absolute'
    boardDiv.style.left='160px'
    boardDiv.style.top='80px'
    holdDiv.id='div_boardhold'
    holdDiv.style.position='absolute'
    holdDiv.style.left='80px'
    holdDiv.style.top='80px'
    nextDiv.id='div_boardnext'
    nextDiv.style.position='absolute'
    nextDiv.style.left='400px'
    nextDiv.style.top='80px'
    statusDiv.id='div_gamestatus'
    statusDiv.style.position='relative'
    statusDiv.style.left='400px'
    statusDiv.style.top='160px'
    mainDiv.appendChild(boardDiv)
    mainDiv.appendChild(holdDiv)
    mainDiv.appendChild(nextDiv)
    mainDiv.appendChild(statusDiv)
    document.body.appendChild(mainDiv)
    tetris=new Tetris
})
