(function(
    color,
    size,
    y_initial__relative,
    name,
    array,
    wallkickdata
){
    this.color=color
    this.size=size
    this.y_initial__relative=y_initial__relative
    this.name=name
    this.array=array
    this.wallkickdata=wallkickdata
})
